spring:
  banner:
    location: "classpath:banner.txt"

  datasource:
    initialization-mode: always
    platform: h2

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: false
        format_sql: false
