spring:
  datasource:
    data: "classpath:data.sql"
    schema: "classpath:schema.sql"
    username: "SA"
    password: ""
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:test"

  banner:
    location: "classpath:banner.txt"
