DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE AUTHOR(
    ID NUMBER(22,0) AUTO_INCREMENT PRIMARY KEY,
    SURNAME VARCHAR(100) not null,
    FIRST_NAME VARCHAR(100) not null,
    SECOND_NAME VARCHAR(100)
);

CREATE TABLE GENRE(
    ID NUMBER(22,0) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) not null
);

CREATE TABLE BOOK(
    ID NUMBER(22,0) AUTO_INCREMENT PRIMARY KEY,
    ADD_RECORD_DATE DATE,
    CAPTION VARCHAR(255) not null,
    AUTHOR_ID INT not null,
    GENRE_ID INT not null,
    COMMENT VARCHAR(255),

    foreign key (AUTHOR_ID) references AUTHOR(ID),
    foreign key (GENRE_ID) references GENRE(ID)
);

