DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ADD_RECORD_DATE DATE,
    CAPTION VARCHAR(255) not null,
    AUTHOR_ID INT not null,
    GENRE_ID INT not null,
    COMMENT VARCHAR(255)
);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SURNAME VARCHAR(100) not null,
    FIRST_NAME VARCHAR(100) not null,
    SECOND_NAME VARCHAR(100)
);

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) not null
);