DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
    ID INT PRIMARY KEY,
    ADD_RECORD_DATE DATE,
    CAPTION VARCHAR(255),
    AUTHOR_ID INT,
    GENRE_ID INT,
    COMMENT VARCHAR(255)
);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
    ID INT PRIMARY KEY,
    SURNAME VARCHAR(100),
    FIRST_NAME VARCHAR(100),
    SECOND_NAME VARCHAR(100)
);

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(
   ID INT PRIMARY KEY,
   NAME VARCHAR(100),
);